#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
      - dev

# yaml dosyalarında yeni bir profil oluşturmak için "---" kullanılır.
---
spring:
  config:
    activate:
      on-profile: production
hoaxify:
  upload-path: storage-production

---
spring:
  config:
    activate:
      on-profile: dev
hoaxify:
  upload-path: storage-dev